print('ingresa tu nombre')
nom = input()
print(nom,'ingresa un numero entero')
ent = input()
print(nom,"ingresa un numero decimal")
dec = input()
print(nom,"ingresa una palabra")
palabra = input()
print(ent)
print(dec)
print(palabra)
print(" ")


n1 = float(input('por favor ingrese un numero: '))
n2 = float(input('por favor ingrese otro numero: '))


print("el resultado de la suma es", n1 + n2)
print("el resultado de la resta es", n1-n2)
print("el resultado de la multiplicacion es", n1*n2)
print("el resultado de la division es", n1/n2)
print("el resultado de la division es", n1/n2)
print("el resultado de la potencia es", n1**n2)
print("el resultado raiz es", (n1**(1/2)))